# Generated by Django 4.1.7 on 2023-04-23 20:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_Crianca',
            fields=[
                ('nr_nascido_vivo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_crianca', models.TextField()),
                ('cpf_crianca', models.IntegerField(blank=True, max_length=11, null=True)),
                ('data_nasc', models.DateField()),
                ('cidade', models.TextField()),
                ('estado', models.TextField()),
                ('cep', models.TextField()),
                ('bairro', models.TextField()),
                ('rua', models.TextField()),
                ('numero', models.TextField()),
                ('nr_cartao_sus', models.IntegerField()),
                ('sexo', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outro', 'Outro')], max_length=20)),
                ('etnia', models.CharField(choices=[('Branca', 'Branca'), ('Negra', 'Negra'), ('Amarela', 'Amarela'), ('Parda', 'Parda'), ('Indígena', 'Indígena'), ('Outra', 'Outra')], max_length=20)),
                ('tipo_sanguineo', models.TextField()),
                ('nome_mae', models.TextField()),
                ('nome_pai', models.TextField(blank=True)),
                ('data_criacao_registro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'cadastro_crianca',
            },
        ),
        migrations.CreateModel(
            name='Cadastro_Funcionario',
            fields=[
                ('id_funcionario', models.AutoField(primary_key=True, serialize=False)),
                ('nome_funcionario', models.TextField()),
                ('cpf_funcionario', models.IntegerField()),
                ('tipo_documento', models.CharField(choices=[('CRM', 'CRM'), ('COREN', 'COREN')], max_length=20)),
                ('numero_documento', models.IntegerField()),
            ],
            options={
                'db_table': 'cadastro_funcionario',
            },
        ),
        migrations.CreateModel(
            name='Unidade_Atentimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_unidade', models.TextField()),
            ],
            options={
                'db_table': 'unidade_atendimento',
            },
        ),
        migrations.CreateModel(
            name='Cadastro_Vacina_Aplicada',
            fields=[
                ('id_vacina', models.AutoField(primary_key=True, serialize=False)),
                ('nome_vacina', models.TextField()),
                ('data_aplicacao', models.DateField()),
                ('lote', models.IntegerField()),
                ('lab_produtor', models.TextField()),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cadastro_crianca')),
                ('dados_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cadastro_funcionario')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidade_atentimento')),
            ],
            options={
                'db_table': 'cadastro_vacina_aplicada',
            },
        ),
        migrations.CreateModel(
            name='Cadastro_Evolucao_Crianca',
            fields=[
                ('id_evolucao', models.AutoField(primary_key=True, serialize=False)),
                ('data_avaliacao', models.DateField()),
                ('idade_anos', models.IntegerField()),
                ('idade_meses', models.IntegerField()),
                ('peso', models.FloatField()),
                ('estatura', models.FloatField()),
                ('perimetro_cefalico', models.FloatField()),
                ('imc', models.FloatField()),
                ('pressao_arterial', models.FloatField()),
                ('classificacao_imc', models.TextField()),
                ('temperatura', models.FloatField()),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cadastro_crianca')),
            ],
            options={
                'db_table': 'cadastro_evolucao_crianca',
            },
        ),
        migrations.CreateModel(
            name='Cadastro_Consultas',
            fields=[
                ('id_consulta', models.AutoField(primary_key=True, serialize=False)),
                ('data_consulta', models.DateField()),
                ('descricao', models.TextField()),
                ('obs', models.TextField(blank=True)),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cadastro_crianca')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cadastro_funcionario')),
                ('unidade_atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidade_atentimento')),
            ],
            options={
                'db_table': 'cadastro_consulta',
            },
        ),
    ]
