# Generated by Django 4.1.7 on 2023-05-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_evolucao_crianca',
            name='classificacao_imc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro_evolucao_crianca',
            name='imc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
