# Generated by Django 4.1.7 on 2023-05-27 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cadastro_evolucao_crianca_classificacao_imc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro_consultas_medicas',
            name='medico',
        ),
    ]
