# Generated by Django 4.1.7 on 2023-05-27 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_cadastro_consultas_medicas_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro_consultas_medicas',
            name='medico',
            field=models.ForeignKey(default=25052023, on_delete=django.db.models.deletion.CASCADE, to='core.cadastro_funcionario'),
            preserve_default=False,
        ),
    ]
