# Generated by Django 4.1.7 on 2023-06-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_procedimento_cadastro_consultas_odontologicas_procedimento_orientacoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observacoes',
            fields=[
                ('id_obs', models.AutoField(primary_key=True, serialize=False)),
                ('data_obs', models.DateField(blank=True, null=True)),
                ('inter_obs', models.TextField(blank=True, null=True)),
                ('obs', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'obervacoes',
            },
        ),
    ]
