# Generated by Django 4.1.7 on 2023-06-07 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacoes',
            name='crianca',
            field=models.ForeignKey(default=222, on_delete=django.db.models.deletion.CASCADE, to='core.cadastro_crianca'),
            preserve_default=False,
        ),
    ]
