# Generated by Django 4.1.7 on 2023-06-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_observacoes_crianca'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro_crianca',
            name='termo_consentimento',
            field=models.BooleanField(null=True),
        ),
    ]
