# Generated by Django 4.1.7 on 2023-06-18 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cadastro_crianca_termo_consentimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro_crianca',
            name='termo_consentimento',
        ),
    ]
