# Generated by Django 4.1.7 on 2023-06-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_cadastro_crianca_termo_consentimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro_crianca',
            name='termo_consentimento',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
