# Generated by Django 4.1.7 on 2023-06-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cadastro_crianca_termo_consentimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_crianca',
            name='tipo_moradia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
